CREATE TABLE VENTAS (
    IDVENTAS INT IDENTITY(1,1) NOT NULL,
    FECHAVENTA DATE NOT NULL,
    TOTALVENTA DECIMAL(10, 2)NOT NULL,
	PRIMARY KEY (IDVENTAS)
);

CREATE TABLE PRODUCTO (
    IDPRODUCTO INT IDENTITY(1,1) NOT NULL,
    NOMBREPRODUCTO NVARCHAR(100) NOT NULL,
    PRECIOUNITARIO DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (IDPRODUCTO)
);

CREATE TABLE DETALLEVENTA (
    IDDETALLEVENTA INT IDENTITY(1,1) NOT NULL,
    IDVENTAS INT NOT NULL,
    IDPRODUCTO INT NOT NULL,
    CANTIDAD INT NOT NULL,
    PRECIOUNITARIO DECIMAL(10, 2) NOT NULL,
    TOTALDETALLE DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (IDDETALLEVENTA),
    FOREIGN KEY (IDVENTAS) REFERENCES VENTAS(IDVENTAS),
    FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO(IDPRODUCTO)
);

INSERT INTO VENTAS (FECHAVENTA, TOTALVENTA)
VALUES ('2024-04-04', 250.75);
INSERT INTO PRODUCTO (NOMBREPRODUCTO, PRECIOUNITARIO)
VALUES ('Zapatos deportivos', 49.99);

INSERT INTO DETALLEVENTA (IDVENTAS, IDPRODUCTO, CANTIDAD, PRECIOUNITARIO, TOTALDETALLE)
VALUES (1, 1, 5, 49.99, 249.95);

INSERT INTO VENTAS (FECHAVENTA, TOTALVENTA)
VALUES ('2024-04-05', 180.50);

INSERT INTO PRODUCTO (NOMBREPRODUCTO, PRECIOUNITARIO)
VALUES ('Camiseta de algodón', 19.99);

INSERT INTO DETALLEVENTA (IDVENTAS, IDPRODUCTO, CANTIDAD, PRECIOUNITARIO, TOTALDETALLE)
VALUES (2, 2, 3, 19.99, 59.97);

INSERT INTO VENTAS (FECHAVENTA, TOTALVENTA)
VALUES ('2024-04-06', 310.20);

INSERT INTO PRODUCTO (NOMBREPRODUCTO, PRECIOUNITARIO)
VALUES ('Gafas de sol', 39.99);


INSERT INTO DETALLEVENTA (IDVENTAS, IDPRODUCTO, CANTIDAD, PRECIOUNITARIO, TOTALDETALLE)
VALUES (3, 3, 4, 39.99, 159.96);
